service: my-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  environment:
    NODE_ENV: development

functions:
  app:
    handler: ./api/api.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline